
export const authConstants ={
    LOGIN_REQUEST: "USER_LOGIN_REQUEST",
    LOGIN_SUCCESS: "USER_LOGIN_SUCCESS",
    LOGIN_FAILURE: "USER_LOGIN_FAILURE",

    CLEAR_ERRORS: "USER_CLEAR_LOGIN_ERRORS",

    RESET_REGISTERED:"RESET_REGISTERED",

    REGISTER_REQUEST: "USER_REGISTER_REQUEST",
    REGISTER_SUCCESS: "USER_REGISTER_SUCCESS",
    REGISTER_FAILURE: "USER_REGISTER_FAILURE",

    RESET_LINK_REQUEST: "RESET_LINK_REQUEST",
    RESET_LINK_SUCCESS: "RESET_LINK_SUCCESS",
    RESET_LINK_FAILURE: "RESET_LINK_FAILURE",

    CLEAR_TOAST : "CLEAR_TOAST",

    CLEAR_STATE : "CLEAR_STATE",

    LOGOUT: "LOGOUT",

    GET_TOKEN : "USER_GET_TOKEN",
    SAVE_TOKEN : "USER_SAVE_TOKEN",
    DELETE_TOKEN : "USER_DELETE_TOKEN",



}