export const gameConstants = {
  GET_CAT_REQUEST: "GET_CAT_REQUEST",
  GET_CAT_SUCCESS: "GET_CAT_SUCCESS",
  GET_CAT_FAILURE: "GET_CAT_FAILURE",

  CLEAR_ANSWER: "CLEAR_ANSWER",

  CLEAR_STATE: "CLEAR_STATE",

  GET_LEADERBOARD_REQUEST: "GET_LEADERBOARD_REQUEST",
  GET_LEADERBOARD_SUCCESS: "GET_LEADERBOARD_SUCCESS",
  GET_LEADERBOARD_FAILURE: "GET_LEADERBOARD_FAILURE",

  GET_WINS_REQUEST: "GET_WINS_REQUEST",
  GET_WINS_SUCCESS: "GET_WINS_SUCCESS",
  GET_WINS_FAILURE: "GET_WINS_FAILURE",

  GET_BUNDLES_REQUEST: "GET_BUNDLES_REQUEST",
  GET_BUNDLES_SUCCESS: "GET_BUNDLES_SUCCESS",
  GET_BUNDLES_FAILURE: "GET_BUNDLES_FAILURE",

  REGISTER_BANK_REQUEST: "REGISTER_BANK_REQUEST",
  REGISTER_BANK_SUCCESS: "REGISTER_BANK_SUCCESS",
  REGISTER_BANK_FAILURE: "REGISTER_BANK_FAILURE",

  CLEAR_PAYMENT: "CLEAR_PAYMENT",

  BUY_KOINS_REQUEST: "BUY_KOINS_REQUEST",
  BUY_KOINS_SUCCESS: "BUY_KOINS_SUCCESS",
  BUY_KOINS_FAILURE: "BUY_KOINS_FAILURE",

  ADD_POINTS: "ADD_POINTS",

  START_GAME_REQUEST: "START_GAME_REQUEST",
  START_GAME_SUCCESS: "START_GAME_SUCCESS",
  START_GAME_FAILURE: "START_GAME_FAILURE",

  STOP_GAME_REQUEST: "STOP_GAME_REQUEST",
  STOP_GAME_SUCCESS: "STOP_GAME_SUCCESS",
  STOP_GAME_FAILURE: "STOP_GAME_FAILURE",

  SUBMIT_REQUEST: "SUBMIT_REQUEST",
  SUBMIT_FAILURE: "SUBMIT_FAILURE",
  SUBMIT_SUCCESS: "SUBMIT_SUCCESS",

  RESET_QA: "RESET_QA",

  GET_TQ: "GET_TQ",
  GET_AQ: "GET_AQ",
  INCREMENT_AQ: "INCREMENT_AQ",
};
