export const userConstants = {
  GET_PLAYER: "GET_PLAYER",
  SAVE_PLAYER: "SAVE_PLAYER",
  DELETE_PLAYER: "DELETE_PLAYER",

  UPDATE_PROFILE_REQUEST: "UPDATE_PROFILE_REQUEST",
  UPDATE_PROFILE_SUCCESS: "UPDATE_PROFILE_SUCCESS",
  UPDATE_PROFILE_FAILURE: "UPDATE_PROFILE_FAILURE",

  UPDATE_DP_REQUEST: "UPDATE_DP_REQUEST",
  UPDATE_DP_SUCCESS: "UPDATE_DP_SUCCESS",
  UPDATE_DP_FAILURE: "UPDATE_DP_FAILURE",

  REFRESH_PLAYER_REQUEST: "REFRESH_PLAYER_REQUEST",
  REFRESH_PLAYER_SUCCESS: "REFRESH_PLAYER_SUCCESS",
  REFRESH_PLAYER_FAILURE: "REFRESH_PLAYER_FAILURE",

  CLEAR_TOAST: "CLEAR_TOAST",

  CLEAR_STATE: "CLEAR_STATE",
};
