require_relative '../node_modules/@react-native-community/cli-platform-ios/native_modules'
require_relative '../node_modules/react-native/scripts/react_native_pods'

platform :ios, '10.0'

target 'kick' do
  config = use_native_modules!
  use_react_native!(:path => config["reactNativePath"])

  pod 'react-native-netinfo', :path => '../node_modules/@react-native-community/netinfo'
  pod 'RNVectorIcons', :path => '../node_modules/react-native-vector-icons'
  pod 'Google-Mobile-Ads-SDK', '7.69.0'
  

  pod 'RNFBMessaging', :path => '../node_modules/@react-native-firebase/messaging'

  target 'kickTests' do
    inherit! :complete
    # Pods for testing
  end

  # Enables Flipper.
  #
  # Note that if you have use_frameworks! enabled, Flipper will not work and
  # you should disable these next few lines.
 

  use_flipper!({ 'Flipper-Folly' => '2.5.3', 'Flipper' => '0.87.0', 'Flipper-RSocket' => '1.3.1' })
  post_install do |installer|
    flipper_post_install(installer)
  end
end

target 'kick-tvOS' do
  # Pods for kick-tvOS

  target 'kick-tvOSTests' do
    inherit! :search_paths
    # Pods for testing
  end
end